# 2023-02-12

# https://github.com/orgs/community/discussions/26323

name: "trigger-01"

on:
  push:
    branches: [ "main" ]
    # branches: [ "nonexistent" ]
  # pull_request:
  #   # The branches below must be a subset of the branches above
  #   branches: [ "main" ]
  # schedule:
  #   - cron: '39 7 * * 2'

jobs:
  Trigger:
    name: Trigger Another Workflow
    runs-on: ubuntu-latest
    steps:
#      - run: |
#          set -ux
#          USER_NAME='solita-sv'
#          REPO_NAME='sv-security-scans-03'
#          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
#            -H "Accept: application/vnd.github.everest-preview+json" \
#            -H "Content-Type: application/json" \
#            https://api.github.com/repos/${USER_NAME}/${REPO_NAME}/dispatches \
#              --data '{"event_type": "build_application"}'
      # - run: |
      #     set -ux
      #     USER_NAME='solita-sv'
      #     REPO_NAME='sv-security-scans-03'
      #     # https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28
      #     curl \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer ${{ secrets.PAT_2023_02_12 }}" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       https://api.github.com/repos/${USER_NAME}/${REPO_NAME}/actions/workflows

      # gh api -H "Accept: application/vnd.github+json" /repos/solita-sv/sv-security-scans-03/actions/workflows

      - run: |
          set -ux
          ORGANIZATION='solita'  # TODO: not solita-sv
          REPOSITORY='sv-security-scans-03'
          curl -H "Authorization: Bearer ${{ secrets.PAT_2023_02_12 }}" \
            https://api.github.com/repos/${ORGANIZATION}/${REPOSITORY}/actions/workflows

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_2023_02_12 }}
          script: |
            set -ux
            ORGANIZATION='solita'  # TODO: not solita-sv
            REPOSITORY='sv-security-scans-03'
            await github.rest.actions.createWorkflowDispatch({
              owner: 'solita-sv',
              repo: 'sv-security-scans-03',
              workflow_id: 48177153,
              ref: 'main',
              debug: true
            })

