# 2023-02-12

# https://github.com/orgs/community/discussions/26323

name: "trigger-01"

on:
  push:
    branches: [ "main" ]
    # branches: [ "nonexistent" ]
  # pull_request:
  #   # The branches below must be a subset of the branches above
  #   branches: [ "main" ]
  # schedule:
  #   - cron: '39 7 * * 2'

jobs:
  Trigger:
    name: Trigger Another Workflow
    runs-on: ubuntu-latest
    steps:
#      - run: |
#          set -ux
#          USER_NAME='solita-sv'
#          REPO_NAME='sv-security-scans-03'
#          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
#            -H "Accept: application/vnd.github.everest-preview+json" \
#            -H "Content-Type: application/json" \
#            https://api.github.com/repos/${USER_NAME}/${REPO_NAME}/dispatches \
#              --data '{"event_type": "build_application"}'
      - uses: actions/github-script@v6
        with:
          # github-token: ${{ secrets.PAT_TOKEN }}
          github-token: ${{ secrets.SIMPLE_SECRET }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'solita-sv',
              repo: 'sv-security-scans-03',
              workflow_id: 'triggered-02.yml',
              ref: 'main'
            })
